#!/bin/busybox sh

timeout=2

bb() { 
	/bin/busybox $* 
}

special_mounts() {
	for i in mnt proc sys dev tmp run
	do
		bb mkdir -p /$i
	done
	bb mount -t proc     none   $1/proc
	bb mount -t sysfs    none   $1/sys
	bb mount -t devtmpfs udev   $1/dev
	bb mkdir -p $1/dev/pts
	bb mount -t devpts   devpts $1/dev/pts
	bb mount -t tmpfs    tmpfs  $1/tmp
	bb mount -t tmpfs    tmpfs  $1/run
}

enter_shell() {
	echo entering shell..
	export PATH=/bin:/usr/bin:/sbin:/usr/sbin
	special_mounts
	bb --install
	stty erase ^H
	/bin/sh
	/sbin/halt
}

start_from() {
	special_mounts $1
	if [ -x $1/sbin/init ]
	then
		exec /bin/busybox switch_root $1 /sbin/init
	else
		echo "/sbin/init is not executeable. entering shell..."
		enter_shell
	fi
}

echo 
read -p "Hit enter within $timeout seconds to enter shell" -t $timeout dummy && enter_shell

echo
echo Normal startup ...

bb ifconfig eth0 192.168.0.55 netmask 255.255.255.0 up
bb route add default gw 192.168.0.2

bb mkdir /nfs
bb mount -t nfs -o nolock 192.168.0.45:/opt/riscv-root /nfs 

start_from /nfs
