#!/bin/busybox sh
# SPDX-FileCopyrightText: 2019 Stefan Adams <stefan.adams@vipcomag.de>
# SPDX-License-Identifier: GPL-3.0-or-later

TIMEOUT=2
ROOTDEV=/dev/mmcblk0p1

alias bb=/bin/busybox

special_mounts() {
	for i in mnt proc sys dev tmp run
	do
		bb mkdir -p /$i
	done
	if bb [ "$2"x != "noproc"x ]
	then
	bb mount -t proc     none   $1/proc
	fi
	bb mount -t sysfs    none   $1/sys
	bb mount -t devtmpfs udev   $1/dev
	bb mkdir -p $1/dev/pts
	bb mount -t devpts   devpts $1/dev/pts
	bb mount -t tmpfs    tmpfs  $1/tmp
	bb mount -t tmpfs    tmpfs  $1/run
}

enter_shell() {
	echo entering shell..
	export PATH=/bin:/usr/bin:/sbin:/usr/sbin
	special_mounts 
	bb --install
	stty erase ^H
	/bin/sh
	/sbin/reboot -f
}

start_from() {
	special_mounts $1 noproc
	exec /bin/busybox switch_root $1 /sbin/init
	echo "can not execute /sbin/init. entering shell..."
	enter_shell
}

echo 
read -p "Hit enter within $TIMEOUT seconds to enter shell" -t $TIMEOUT dummy && enter_shell

echo
echo Normal startup ...

bb mkdir -p /proc /dev /etc /mnt /sys
bb mount -t proc none /proc
bb mount -t sysfs    none   /sys
bb mount -t devtmpfs udev /dev
bb ln -sf /proc/mounts /etc/fstab

# get partition to boot from devicetree
P=/proc/device-tree/chosen/partition 
if bb [ -f $P ]
then
	PARTNR=`bb cat $P`
	PARTNR=`printf "%d" "'$PARTNR"`
	echo setting boot partition to $PARTNR
	ROOTDEV=/dev/mmcblk0p"$PARTNR"
fi

#NOTE: fsck.ext4 with shared libs makes initramfs huge, rely on ext4 recovery
#/sbin/fsck.ext4 -y $ROOTDEV

# check for virtio disk
bb [ -b $ROOTDEV ] || ROOTDEV=/dev/vda

# check for nfs boot
bb mount $ROOTDEV /mnt || (echo "WARNING: can not mount $ROOTDEV !";bb umount /proc /dev /sys;enter_shell)
bb [ -f /mnt/nfs_boot ] && bb [ -d /proc/sys/fs/nfs ]
START_NFS=$?
bb umount /proc /dev /sys

if bb [ $START_NFS == 0 ]
then
	echo "nfs boot ..."
	BOOTDIR=/nfs

	. /mnt/nfs_boot
	bb umount /mnt

	bb ifconfig eth0 $ADDRESS netmask $NETMASK up
	bb route add default gw $GATEWAY

	bb mkdir /nfs
	bb mount -t nfs -o nolock $MOUNTPOINT /nfs 
else
	echo "sd-card boot ..."
	BOOTDIR=/mnt
fi

start_from $BOOTDIR

