#!/bin/sh
# SPDX-FileCopyrightText: 2019 Esther Bergter <esther.bergter@vipcomag.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
# display    start nxdisplay
#

. /etc/init.d/zsiposfunc

cp /var/log/messages $STARTLOG

PIDFILE=/var/run/nxdisplay.pid

calibrate() {
    if [ ! -f /etc/pointercal ]; then
        export TSLIB_TSDEVICE=/dev/input/event0 
        /usr/bin/ts_calibrate
    fi
}

get_pid() {
    if [ -f $PIDFILE ]; then
        PID=$(sed 's/ //g' $PIDFILE)
    else
        PID=`pidof nxdisplay`
    fi
}

running() {
    get_pid 

    if [ -n "$PID" ]; then
        kill -0 $PID 2>/dev/null && echo y || rm -f $PIDFILE
    fi
}

start() {
    echo -n "Starting display: "
    RUNNING=$(running)
    if [ -z "$RUNNING" ]; then
        calibrate
        rm -f $FIFO
        # nxdisplay legt FIFO an
        /bin/nxdisplay >/var/log/nxdisplay 2>&1 &
        pidof nxdisplay >$PIDFILE
        while test ! -p $FIFO
            do sleep 1
        done
        display "starting display ..."
    fi
    echo OK
}

stop() {
    echo -n "Stopping display: "
    get_pid
    if [ -n "$PID" ]; then
        if [ -n "$PID" ]; then
            kill $PID
            #display "display stopped" # trigger stop
        fi
        test -f $PIDFILE && rm $PIDFILE
    fi
    echo "OK"
}

restart() {
    stop
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
