#!/bin/sh
# SPDX-FileCopyrightText: 2019 Esther Bergter <esther.bergter@vipcomag.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
# zsiposconf    Configure network, ntp
#               Load kernel modules
#               enforce password reset at startup
#

. /etc/init.d/zsiposfunc

start() {
    echo -n "Starting zsiposconf: "
    V=/version.txt
    if [ -f $V ]
    then
        v=`cat $V`
        p=`cat /proc/device-tree/chosen/zsipos,partition`
        display "$v on partition $p"
    fi
    if [ ! -f /root/zsipos_factory.cfg ]; then
        echo "/root/zsipos_factory.cfg missing"
        exit 0
    fi


    display "init zsipos configuration ..."

    CFG=/root/zsipos.cfg
    CFGBAK=/root/zsipos.cfg.bak
    FACTORY=/root/zsipos_factory.cfg
    ZID=/root/zsipos.zid
    NDB=/root/zsipos.ndb
    NTP=/etc/chrony.conf
    NTPFACTORY=/etc/chrony_factory.conf

    # Initial startup or reset
    if [ ! -f $CFG ]; then
         cp $FACTORY $CFG
         # Factory reset
         rm -f $ZID
         rm -f $NDB
         touch /root/pw_reset
         # make sure passwd has a date > 0
         date | grep 1970 && date +%d%m%Y -s "11112011"
    fi

    # some error deleted zsipos.cfg
    if [ ! -s /root/zsipos.cfg ]; then
        if [ -s $CFGBAK ] ; then
            cp $CFGBAK $CFG
        else
            cp $FACTORY $CFG
        fi
    fi

    # the network
    DHCP=$(grep -i '^externalUseDHCP\s*=\s*True' $CFG)
    DNSSERVER=$(sed -n '/^dnsServer/ s/dnsServer\s*=\s*// p' $CFG)
    LOCALPROXY=$(sed -n '/^localProxyAddress/ s/localProxyAddress\s*=\s*// p' $CFG)
    LOCALNET=$(sed -n '/^localNetmask/ s/localNetmask\s*=\s*// p' $CFG)
    GATEWAY=$(sed -n '/^externalGateway/ s/externalGateway\s*=\s*// p' $CFG)
    ETH0=$(sed -n '/^externalPhoneAddress/ s/externalPhoneAddress\s*=\s*// p' $CFG)
    NETMASK=$(sed -n '/^externalNetmask/ s/externalNetmask\s*=\s*// p' $CFG)
    NTPSERVER=$(sed -n '/^ntpServer/ s/ntpServer\s*=\s*// p' $CFG)
    if [ -z "$LOCALNET" ]; then
        LOCALNET=255.255.255.0
    fi
    if [ -z "$NETMASK" ]; then
        NETMASK=255.255.255.0
    fi
    if [ -z "$ETH0" ]; then
        DHCP=on
    fi

    cat >/etc/network/interfaces <<EOF
# Configure Loopback
auto lo
iface lo inet loopback

EOF

    if [ -n "$DHCP" ]; then
        cat >>/etc/network/interfaces <<EOF
#Configure eth0 with dhcp IP
auto eth0
iface eth0 inet dhcp
EOF
    else
        cat >>/etc/network/interfaces <<EOF
#Configure eth0 with static IP
auto eth0
iface eth0 inet static
    address $ETH0
    netmask $NETMASK
EOF
        if [ -n "$GATEWAY" ]; then
            cat >>/etc/network/interfaces <<EOF
    gateway $GATEWAY
EOF
        fi
    fi

    # key dns-nameservers is not handled anyway

    cat >>/etc/network/interfaces <<EOF
#Configure eth1 static local proxy
auto eth1
iface eth1 inet static
    address $LOCALPROXY
    netmask $LOCALNET
EOF

    # ntp daemon
    if [ -n "$NTPSERVER" ]; then
        cat >$NTP <<EOF
server $NTPSERVER
EOF
        fgrep -v server $NTPFACTORY | fgrep -v bindaddress >>$NTP
        cat >>$NTP <<EOF
bindaddress $LOCALPROXY
EOF
    else
        fgrep -v bindaddress $NTPFACTORY >$NTP
        cat >>$NTP <<EOF
bindaddress $LOCALPROXY
EOF
    fi

    # resolv.conf (mit und ohne) DHCP, wenn DNSSERVER gegeben
    if [ -n "$DNSSERVER" ]; then
        cat >/etc/resolv.conf <<EOF
nameserver $DNSSERVER
EOF
    else
        echo >/etc/resolv.conf # empty file
    fi

    # different ip configuration for sel4ip stack
    if [ -f /proc/net/stack ]
    then
	if [ -n "$DHCP" ]
	then
		if [ -n "$DNSSERVER" ]
		then
			DNSOUT="/dev/null"
		else
			DNSOUT="/etc/resolv.conf"
		fi
		DHCPDISP=" (DHCP) "
		IF0CMD1="/bin/sel4iptool eth0 dhcp >$DNSOUT"
		IF0CMD2="#"
	else
		DHCPDISP=""
		IF0CMD1="ifconfig eth0 $ETH0 netmask $NETMASK"
		IF0CMD2="route add default gw $GATEWAY"
	fi
	cat >/etc/init.d/S40network <<EOF
#!/bin/sh
# This file is auto-generated. Please do not edit.
. /etc/init.d/zsiposfunc
case "\$1" in
start)
       	echo "Starting network: "
	display "starting network $DHCPDISP..."
	$IF0CMD1
	$IF0CMD2
	ifconfig eth1 $LOCALPROXY netmask $LOCALNET up
	echo "OK"
	;;
stop)
	printf "Stopping network: "
	ifconfig eth0 down
	ifconfig eth1 down
	echo "OK"
	;;
restart|reload)
	"\$0" stop
	"\$0" start
	;;
*)
	echo "Usage: \$0 {start|stop|restart}"
	exit 1
esac
exit 0
EOF
	chmod ugo+xr /etc/init.d/S40network
    fi

    echo OK
}

stop(){
    echo "Stopping zsiposconf: OK"
}
restart() {
    stop
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

