#!/bin/sh
# SPDX-FileCopyrightText: 2019 Esther Bergter <esther.bergter@vipcomag.de>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
# zsiposconf2   configure steps after ntp is up , before sshd starts
#
# reset root password if required (needs valid time)
#

. /etc/init.d/zsiposfunc

start() {
    display "checking network status ..."
    MYIP=`ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | cut -d ' ' -f 1`
    display "network is up, my IP Address is $MYIP"
}

stop(){
    display "going down"
}

restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

