#!/bin/sh

# SPDX-FileCopyrightText: 2019 Stefan Adams <stefan.adams@vipcomag.de>
# SPDX-License-Identifier: GPL-3.0-or-later

mkdir -p /run/network

case "$1" in
  start)
	printf "Starting network: "
	ifconfig eth0 192.168.0.55 netmask 255.255.255.0 up
	route add default gw 192.168.0.2
	echo "OK"
	;;
  stop)
	printf "Stopping network: "
	ifconfig eth0 down
	echo "OK"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

